---
- name: Load customer specific vars if in brisbane_isuzu group
  include_vars:
    file: "/etc/ansible/inventory/group_vars/brisbane_isuzu.yml"
  when: "'brisbane_isuzu' in group_names"

- name: Ensure tree is installed
  package:
    name: tree
    state: present
